services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./bots.json:/app/bots.json
    env_file:
      - .env
